name: "Build, Test and Run"

on: ["push", "pull_request"]

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out source code"
        uses: "actions/checkout@v3"

      - name: "Setup JDK 8"
        uses: "actions/setup-java@v3"
        with:
          java-version: "8"
          distribution: "corretto"

      - name: "Validate Gradle Wrapper"
        uses: "gradle/wrapper-validation-action@v1"

      - name: "Setup Gradle"
        uses: "gradle/gradle-build-action@v2"

      - name: "Build with Gradle"
        run: "gradle build"

      - name: "Upload 'AdventOfCode.jar'"
        uses: "actions/upload-artifact@v3"
        with:
          name: "AdventOfCode.jar"
          path: "build/libs/AdventOfCode.jar"

  run:
    name: "Run"
    needs: ["build-and-test"]
    runs-on: "macos-latest"

    steps:
      - name: "Download 'AdventOfCode.jar'"
        uses: "actions/download-artifact@v3"
        with:
          name: "AdventOfCode.jar"

      - name: "Setup JDK 8"
        uses: "actions/setup-java@v3"
        with:
          java-version: "8"
          distribution: "corretto"

      - name: "Run 'AdventOfCode.jar'"
        run: "java -jar AdventOfCode.jar"
